# Generated by Django 4.1.2 on 2023-02-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaAutos', '0009_alter_slide_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
